parser: babel-eslint
extends:
- airbnb
env:
  mocha: true
rules:
  max-len:
  - warn
  - code: 120
    ignoreTrailingComments: true
    ignoreUrls: true
  padded-blocks: 0
  react/prop-types: 0
  semi:
  - error
  - never
  space-unary-ops:
  - error
  - overrides:
      "!": true
  quote-props: 0
  no-confusing-arrow: 0
  no-unused-expressions: 0
  no-underscore-dangle: 0
  no-param-reassign:
  - error
  - props: false
  no-trailing-spaces: 0
  import/named: error
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  import/no-unresolved:
  - error
  - ignore:
    - "^react$"  # since we can't install it as a dependency
    - "^react-dom$"
  react/no-did-mount-set-state: 0
ecmaFeatures:
  spread: true
